#!/usr/bin/env bash
#
# One-command AWS deployment for didactic-dashboard.
#
#   ./deploy.sh           create the VM (Terraform) and configure it (Ansible)
#   ./deploy.sh destroy   tear everything down
#
# By default only YOUR current public IP may SSH into the VM. To allow a
# different range:  ADMIN_CIDR=203.0.113.0/24 ./deploy.sh

set -euo pipefail

# Everything below uses paths relative to this script, so it works no matter
# which directory you call it from.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

HARDENING_REPO="https://github.com/DannyRuizB/debian-hardening-ansible"
# Pinned commit of the hardening roles — they run as root on the host, so
# upgrades must be deliberate (bump the ref and test), same policy as app_tag.
HARDENING_REF="2d71745427a82ba3db5a3d063ba9375615b72ed7"
VENDOR_DIR="ansible/vendor/debian-hardening-ansible"

# --- 1. Sanity checks --------------------------------------------------------

for tool in terraform ansible-playbook aws git curl; do
  if ! command -v "$tool" >/dev/null 2>&1; then
    echo "ERROR: '$tool' is not installed (or not in PATH)." >&2
    exit 1
  fi
done

# Fails fast if 'aws configure' was never run or the credentials expired.
if ! aws sts get-caller-identity >/dev/null 2>&1; then
  echo "ERROR: AWS credentials do not work. Run 'aws configure' first." >&2
  exit 1
fi

# --- Destroy mode -------------------------------------------------------------

if [[ "${1:-}" == "destroy" ]]; then
  # destroy needs an initialized working dir too (fresh checkout, cleaned cache).
  if [[ ! -d terraform/.terraform ]]; then
    terraform -chdir=terraform init
  fi
  # admin_cidr has no default, so Terraform asks for it even on destroy.
  # Its value is irrelevant when deleting, so pass a placeholder instead of
  # depending on an internet lookup that could fail.
  terraform -chdir=terraform destroy -var "admin_cidr=${ADMIN_CIDR:-127.0.0.1/32}"
  exit 0
fi

# --- 2. Who is allowed to SSH in? --------------------------------------------

# The security group opens port 22 only to this CIDR (see terraform/main.tf).
# A garbage value here (e.g. an error page from the IP service) would create
# the security group with the wrong CIDR and lock us out of SSH, so validate.
if [[ -z "${ADMIN_CIDR:-}" ]]; then
  MY_IP="$(curl -fsS ifconfig.me)" || {
    echo "ERROR: could not look up your public IP. Set ADMIN_CIDR manually:" >&2
    echo "       ADMIN_CIDR=<your-ip>/32 ./deploy.sh" >&2
    exit 1
  }
  if [[ ! "$MY_IP" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    echo "ERROR: 'ifconfig.me' returned '$MY_IP', not an IPv4 address." >&2
    echo "       Set ADMIN_CIDR manually: ADMIN_CIDR=<your-ip>/32 ./deploy.sh" >&2
    exit 1
  fi
  ADMIN_CIDR="$MY_IP/32"
fi
echo "==> SSH will be allowed from: $ADMIN_CIDR"

# --- 3. Terraform: create the VM ----------------------------------------------

# 'init' downloads the AWS provider — only needed the first time.
if [[ ! -d terraform/.terraform ]]; then
  terraform -chdir=terraform init
fi

# Terraform shows the plan and asks for confirmation before creating anything.
terraform -chdir=terraform apply -var "admin_cidr=$ADMIN_CIDR"

PUBLIC_IP="$(terraform -chdir=terraform output -raw public_ip)"
echo "==> Instance is up at $PUBLIC_IP"

# --- 4. Wait for SSH -----------------------------------------------------------

# The instance exists but sshd may take a minute to answer. Try every 10 s for
# up to 5 minutes. Host key checks are skipped on purpose: this is a throwaway
# VM whose key is new on every deploy (Ansible skips them too, see ansible.cfg).
echo "==> Waiting for SSH on $PUBLIC_IP ..."
for attempt in $(seq 1 30); do
  if ssh -i "$HOME/.ssh/id_ed25519" \
      -o BatchMode=yes -o ConnectTimeout=5 \
      -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
      "admin@$PUBLIC_IP" true 2>/dev/null; then
    echo "==> SSH is ready."
    break
  fi
  if [[ "$attempt" -eq 30 ]]; then
    echo "ERROR: SSH on $PUBLIC_IP never came up." >&2
    exit 1
  fi
  sleep 10
done

# --- 5. Ansible: harden the host + run the container ---------------------------

# Real inventory, generated from the Terraform output. ansible_user must live
# here and not in a -u flag — inventory.example.ini explains why.
cat > ansible/inventory.ini <<EOF
# Generated by deploy.sh — regenerated on every run, do not edit.
[dashboard]
$PUBLIC_IP ansible_user=admin ansible_ssh_private_key_file=~/.ssh/id_ed25519
EOF

# The hardening roles come from a plain playbook repo with no Galaxy metadata,
# so ansible-galaxy cannot install it — we vendor it with git instead and
# ansible.cfg points roles_path at the clone. Checked out at HARDENING_REF,
# never a branch tip: two runs of this script must harden the host identically.
if [[ ! -d "$VENDOR_DIR" ]]; then
  git clone "$HARDENING_REPO" "$VENDOR_DIR"
fi
git -C "$VENDOR_DIR" fetch --quiet origin
git -C "$VENDOR_DIR" checkout --quiet "$HARDENING_REF"

# Run from ansible/ so ansible.cfg is picked up. Collections install into
# ansible/collections/ (collections_path) — nothing touches your ~/.ansible.
(
  cd ansible
  ansible-galaxy collection install -r requirements.yml -p ./collections
  ansible-playbook site.yml
)

# --- 6. Done --------------------------------------------------------------------

echo
echo "=================================================================="
echo "  Dashboard : $(terraform -chdir=terraform output -raw app_url)"
echo "  SSH       : $(terraform -chdir=terraform output -raw ssh_command)"
echo "=================================================================="
